// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDIV7sn6PLo2tm1AKpQTZkXQiW71zPZJ7Q',
    appId: '1:196434391051:web:1a2d62ab8cacc2fb09d70e',
    messagingSenderId: '196434391051',
    projectId: 'timekeeper-213fb',
    authDomain: 'timekeeper-213fb.firebaseapp.com',
    storageBucket: 'timekeeper-213fb.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAXcIUrcHA5_K0tf9do4Mp-VMZMGboDOok',
    appId: '1:196434391051:android:7d7504bbdbb1f77f09d70e',
    messagingSenderId: '196434391051',
    projectId: 'timekeeper-213fb',
    storageBucket: 'timekeeper-213fb.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAv-lldiK07sBhys_6Xv7Zw0ReMolaxS4A',
    appId: '1:196434391051:ios:cf67bbe9cda2959009d70e',
    messagingSenderId: '196434391051',
    projectId: 'timekeeper-213fb',
    storageBucket: 'timekeeper-213fb.appspot.com',
    iosBundleId: 'com.example.timeKeeper',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAv-lldiK07sBhys_6Xv7Zw0ReMolaxS4A',
    appId: '1:196434391051:ios:cf67bbe9cda2959009d70e',
    messagingSenderId: '196434391051',
    projectId: 'timekeeper-213fb',
    storageBucket: 'timekeeper-213fb.appspot.com',
    iosBundleId: 'com.example.timeKeeper',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDIV7sn6PLo2tm1AKpQTZkXQiW71zPZJ7Q',
    appId: '1:196434391051:web:38f921bcede39c2809d70e',
    messagingSenderId: '196434391051',
    projectId: 'timekeeper-213fb',
    authDomain: 'timekeeper-213fb.firebaseapp.com',
    storageBucket: 'timekeeper-213fb.appspot.com',
  );

}